### PR TITLE
fix(plugin): do not overwrite existing cookie in res object

### PR DESCRIPTION
**Pull request by williamchong007**
Currently the cookie setting code overwrite any existing `set-cookie` header in pending response
this PR fixes this by appending it instead

### CODE REVIEW

**Comment by farzadso** [comment]
@pi0 Do you have any opinions on this change? I think appending it is a better practice, unless you have any issues.

**Comment by pi0** [comment]
This is a good fix. We also need it for universal-storage and auth to support multiple Set-Cookie calls in a single response.

**Comment by farzadso** [comment]
@pi0 Will you do the honours for the other modules?

**Comment by pi0** [comment]
@farzadso for auth, I'll add it to current PR.

FYI regarding this change, express also do the same: https://github.com/expressjs/express/blob/b8e50568af9c73ef1ade434e92c60d389868361d/lib/response.js#L731

**Comment by farzadso** [comment]
Thanks Pooya

**Pull request merged**
